Update civicrm.module
civicrm/civicrm-drupal pull request #627
Opened 2020-11-16 22:17 UTC by eileenmcnaughton

@MikeyMJCO probably has a better suggestion.....

2020-11-17 09:47 UTC, MikeyMJCO requested changes

2020-11-17 09:47 UTC, MikeyMJCO commented on civicrm.module
> +    $docLinkInstall = "http://www.sorry-no-idea";
```suggestion
    $docLinkInstall = "https://docs.civicrm.org/installation/en/latest/drupal7/";
```

2020-11-17 09:48 UTC, MikeyMJCO requested changes

2020-11-17 09:48 UTC, MikeyMJCO commented on civicrm.module
>      $docLinkTrouble = "http://wiki.civicrm.org/confluence/display/CRMDOC/Installation+and+Configuration+Trouble-shooting";
```suggestion
    $docLinkTrouble = "https://docs.civicrm.org/installation/en/latest/general/troubleshooting/";
```

2020-11-17 09:48 UTC, MikeyMJCO commented on civicrm.module
>      $forumLink      = "http://forum.civicrm.org/index.php/board,6.0.html";
```suggestion
    $forumLink      = "https://civicrm.stackexchange.com/questions/tagged/drupal";
```

2020-11-18 03:46 UTC, seamuslee001 commented
@eileenmcnaughton are you able to update this PR?

2020-12-03 20:23 UTC, eileenmcnaughton commented
#629 closes

2020-12-03 20:23 UTC, closed without merging